---
title: "Figure 5 - network analysis"
output: html_document
---

Load libraries
```{r warning=FALSE}
library(tidyverse)
library(haven)
library(igraph)
library(ggraph)
library(tidygraph)
library(ggpubr)
```


Load data
```{r}
board_members <- read_dta("d_trustees_long_network_ties_preqinids.dta")
```


Creating visualization (Figure 5)
```{r}
board_members_updated <- board_members %>% 
    mutate(employer_type_aggregated = case_when(
    employer_type_aggregated == "Public sector" ~ "Elected officials, gov-t appointees",
    employer_type_aggregated == "Non-profits/philanthropy" ~ "Non-profits, philanthropy",
    employer_type_aggregated == "Non-financial business" ~ "Non-financial businesses",
    employer_type_aggregated == "Education science medicine" ~ "Education, science, medicine",
    TRUE ~ employer_type_aggregated))

# node list
node_list <- board_members_updated %>% 
  filter(schooltype!="liberal arts") %>% 
  filter(unitid!=232186 & unitid!=126818 & unitid!=209542 & unitid!=221759 & unitid!=102614 & unitid!=129020 & unitid!=181464) %>% 
  filter(!is.na(firmname_new)) %>%
  filter(employer_type_aggregated!="Unknown_sector") %>% 
  select(firmname_new, employer_type_aggregated) %>% 
  unique() %>% 
  rename(group_from = employer_type_aggregated,
         id = firmname_new)

node_list_new <- node_list %>% rename(group_to = group_from)

## edge list 2017 private  
org_list <- board_members_updated %>% 
  filter(year == 2017) %>% 
  filter(schooltype!="liberal arts") %>% 
  filter(unitid!=232186 & unitid!=126818 & unitid!=209542 & unitid!=221759 & unitid!=102614 & unitid!=129020 & unitid!=181464) %>% 
  filter(!is.na(firmname_new)) %>% 
  filter(employer_type_aggregated!="Unknown_sector") %>% 
  filter(publicprivate == "Private") %>% 
  group_by(firmname_new, schoolname, employer_type_aggregated) %>% 
  summarise(weight = n()) %>% 
  rename(from = firmname_new,
         to = schoolname,
         group = employer_type_aggregated)

g <- graph.data.frame(org_list, directed = FALSE)
V(g)$type <- V(g)$name %in% org_list$to
organizations <- as_incidence_matrix(g)
organizations <- organizations %*% t(organizations)
diag(organizations) <- 0
g <- graph_from_adjacency_matrix(organizations, mode = "undirected", weighted = TRUE)

org <- get.data.frame(g)
org <- left_join(org, node_list, by = c("from"="id"))
org <- left_join(org, node_list_new, by = c("to"="id"))

edge_list <- org %>% 
  group_by(group_to, group_from) %>% 
  summarise(weight = sum(weight)) %>% 
  rename(from = group_from,
         to = group_to) %>% 
  mutate(weight = ifelse(from==to,NA,weight)) %>% 
  filter(!is.na(weight)) 

g <- graph.data.frame(edge_list, directed = FALSE)
g <- simplify(g, remove.multiple = TRUE)
V(g)$size <- graph.strength(g)  
org_new_2017_private <- get.data.frame(g)

private_2017 <- ggraph(g, layout = 'circle') + 
    geom_edge_fan(aes(width = weight/10, alpha = weight), 
                  show.legend = FALSE, color = "grey") + 
    geom_node_point(aes(size = size, color = name)) + 
    geom_node_text(aes(label = name), size = 14, check_overlap = TRUE, repel = TRUE,
                   nudge_y = -0.1, label.padding = unit(0.1, "lines")) +
    scale_size(range = c(6.6, 49.6)) +
    scale_edge_width_continuous(range = c(6.2, 37.7))+
    theme_graph(fg_text_colour = 'white') +
    theme(legend.position = "none")



## edge list 2017 public
org_list <- board_members_updated %>% 
  filter(year == 2017) %>% 
  filter(schooltype!="liberal arts") %>% 
  filter(unitid!=232186 & unitid!=126818 & unitid!=209542 & unitid!=221759 & unitid!=102614 & unitid!=129020 & unitid!=181464) %>% 
  filter(!is.na(firmname_new)) %>% 
  filter(employer_type_aggregated!="Unknown_sector") %>% 
  filter(publicprivate == "Public") %>% 
  group_by(firmname_new, schoolname, employer_type_aggregated) %>% 
  summarise(weight = n()) %>% 
  rename(from = firmname_new,
         to = schoolname,
         group = employer_type_aggregated)  

g <- graph.data.frame(org_list, directed = FALSE)
V(g)$type <- V(g)$name %in% org_list$to
organizations <- as_incidence_matrix(g)
organizations <- organizations %*% t(organizations)
diag(organizations) <- 0
g <- graph_from_adjacency_matrix(organizations, mode = "undirected", weighted = TRUE)

org <- get.data.frame(g)
org <- left_join(org, node_list, by = c("from"="id"))
org <- left_join(org, node_list_new, by = c("to"="id"))

edge_list <- org %>% 
  group_by(group_to, group_from) %>% 
  summarise(weight = sum(weight)) %>% 
  rename(from = group_from,
         to = group_to) %>% 
  mutate(weight = ifelse(from==to,NA,weight)) %>% 
  filter(!is.na(weight)) 

g <- graph.data.frame(edge_list, directed = FALSE)
g <- simplify(g, remove.multiple = TRUE)
V(g)$size <- graph.strength(g)  
org_new_2017_public <- get.data.frame(g)

public_2017 <- ggraph(g, layout = 'circle') + 
    geom_edge_fan(aes(width = weight/10, alpha = weight), 
                  show.legend = FALSE, color = "grey") + 
    geom_node_point(aes(size = size, color = name)) + 
    geom_node_text(aes(label = name), size = 14, check_overlap = TRUE, repel = TRUE,
                   nudge_y = -0.1, label.padding = unit(0.1, "lines")) +
    scale_size(range = c(2, 12)) +
    scale_edge_width_continuous(range = c(2, 6))+
    theme_graph(fg_text_colour = 'white') +
    theme(legend.position = "none")



## edge list 2003 private  
org_list <- board_members_updated %>% 
  filter(year == 2003) %>% 
  filter(schooltype!="liberal arts") %>% 
  filter(unitid!=232186 & unitid!=126818 & unitid!=209542 & unitid!=221759 & unitid!=102614 & unitid!=129020 & unitid!=181464) %>% 
  filter(!is.na(firmname_new)) %>% 
  filter(employer_type_aggregated!="Unknown_sector") %>% 
  filter(publicprivate == "Private") %>% 
  group_by(firmname_new, schoolname, employer_type_aggregated) %>% 
  summarise(weight = n()) %>% 
  rename(from = firmname_new,
         to = schoolname,
         group = employer_type_aggregated)  

g <- graph.data.frame(org_list, directed = FALSE)
V(g)$type <- V(g)$name %in% org_list$to
organizations <- as_incidence_matrix(g)
organizations <- organizations %*% t(organizations)
diag(organizations) <- 0
g <- graph_from_adjacency_matrix(organizations, mode = "undirected", weighted = TRUE)

org <- get.data.frame(g)
org <- left_join(org, node_list, by = c("from"="id"))
org <- left_join(org, node_list_new, by = c("to"="id"))

edge_list <- org %>% 
  group_by(group_to, group_from) %>% 
  summarise(weight = sum(weight)) %>% 
  rename(from = group_from,
         to = group_to) %>% 
  mutate(weight = ifelse(from==to,NA,weight)) %>% 
  filter(!is.na(weight)) 

g <- graph.data.frame(edge_list, directed = FALSE)
g <- simplify(g, remove.multiple = TRUE)
V(g)$size <- graph.strength(g)  
org_new_2003_private <- get.data.frame(g)

private_2003 <- ggraph(g, layout = 'circle') + 
    geom_edge_fan(aes(width = weight/10, alpha = weight), 
                  show.legend = FALSE, color = "grey") + 
    geom_node_point(aes(size = size, color = name)) + 
    geom_node_text(aes(label = name), size = 14, check_overlap = TRUE, repel = TRUE,
                   nudge_y = -0.1, label.padding = unit(0.1, "lines")) +
    scale_size(range = c(7.2, 42.8)) +
    scale_edge_width_continuous(range = c(5.4, 30.6))+
    theme_graph(fg_text_colour = 'white') +
    theme(legend.position = "none")



## edge list 2003 public
org_list <- board_members_updated %>% 
  filter(year == 2003) %>% 
  filter(schooltype!="liberal arts") %>% 
  filter(unitid!=232186 & unitid!=126818 & unitid!=209542 & unitid!=221759 & unitid!=102614 & unitid!=129020 & unitid!=181464) %>% 
  filter(!is.na(firmname_new)) %>% 
  filter(employer_type_aggregated!="Unknown_sector") %>% 
  filter(publicprivate == "Public") %>% 
  group_by(firmname_new, schoolname, employer_type_aggregated) %>% 
  summarise(weight = n()) %>% 
  rename(from = firmname_new,
         to = schoolname,
         group = employer_type_aggregated)  

g <- graph.data.frame(org_list, directed = FALSE)
V(g)$type <- V(g)$name %in% org_list$to
organizations <- as_incidence_matrix(g)
organizations <- organizations %*% t(organizations)
diag(organizations) <- 0
g <- graph_from_adjacency_matrix(organizations, mode = "undirected", weighted = TRUE)

org <- get.data.frame(g)
org <- left_join(org, node_list, by = c("from"="id"))
org <- left_join(org, node_list_new, by = c("to"="id"))

edge_list <- org %>% 
  group_by(group_to, group_from) %>% 
  summarise(weight = sum(weight)) %>% 
  rename(from = group_from,
         to = group_to) %>% 
  mutate(weight = ifelse(from==to,NA,weight)) %>% 
  filter(!is.na(weight)) 

g <- graph.data.frame(edge_list, directed = FALSE)
g <- simplify(g, remove.multiple = TRUE)
V(g)$size <- graph.strength(g)  
org_new_2003_public <- get.data.frame(g)

public_2003 <- ggraph(g, layout = 'circle') + 
    geom_edge_fan(aes(width = weight/10, alpha = weight), 
                  show.legend = FALSE, color = "grey") + 
    geom_node_point(aes(size = size, color = name)) + 
    geom_node_text(aes(label = name), size = 14, check_overlap = TRUE, repel = TRUE,
                   nudge_y = -0.1, label.padding = unit(0.1, "lines")) +
    scale_size(range = c(1.1, 11.0)) +
    scale_edge_width_continuous(range = c(0.5, 7.2))+
    theme_graph(fg_text_colour = 'white') +
    theme(legend.position = "none")


network <- ggarrange(private_2003, public_2003, private_2017, public_2017,
          #labels = c("2003: Private university network", 
          #           "2003: Public university network",
          #           "2017: Private university network", 
          #           "2017: Public university network"),
          #font.label = list(size = 50, color = "black"),
          ncol = 2, nrow = 2)

ggsave(network, file = "Figure 5.png", width = 40, height = 40)
```


Create file comparing aggregated edge weights between 2017 and 2003
```{r}
org_new_2017_private <- org_new_2017_private %>% 
  mutate(network = "Private university network", year = "year_2017")

org_new_2017_public <- org_new_2017_public %>% 
  mutate(network = "Public university network", year = "year_2017")

org_new_2003_private <- org_new_2003_private %>% 
  mutate(network = "Private university network", year = "year_2003")

org_new_2003_public <- org_new_2003_public %>% 
  mutate(network = "Public university network", year = "year_2003")

org_new_combined <- bind_rows(org_new_2017_private, org_new_2017_public, org_new_2003_private, org_new_2003_public)

rm(org_new_2017_private, org_new_2017_public, org_new_2003_private, org_new_2003_public)

org_new_combined <- org_new_combined %>% 
  pivot_wider(names_from = year, values_from = weight) %>% 
  mutate(change_rate = year_2017/year_2003)

write.csv(org_new_combined, "Network_tie_comparison.csv")
```

